config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"
  get "users/login", to: "users#new", as: "login"
  post "users/login", to: "users#login"
  get "users/logout", to: "users#logout", as: "logout"
  get "posts/my-posts", to: "posts#user_posts", as: "my_posts"
  resources :users, only: [ :show, :new, :create ]
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 4, maximum: 20 }
  validates :body, presence: true, length: { minimum: 4, maximum: 80 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, length: { minimum: 4, maximum: 10 }
  validates :email, presence: true, Uniqueness: true
  validates :password, presence: true, length: { minimum: 4, maximum: 10 }
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def reset_current_user
    @current_user = nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :redirect_if_not_logged_in, only: [ :new, :user_posts ]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to post_path(@post)
    else
      flash.now[:alert] = @post.errors.full_messages.join(" -- ")
      # redirect_to new_post_path
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    redirect_to posts_path unless @post.user == current_user
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post updated."
      redirect_to post_path(@post)
    else
      flash[:alert] = @post.errors.full_messages.join(" -- ")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user == current_user
      @post.destroy
      flash[:notice] = "Post deleted."
      redirect_to posts_path
    end
  end
  def user_posts
    @posts = Post.where(user_id: current_user.id)
    # @posts = Post.includes(:user).where(user: { id: current_user.id })
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def redirect_if_not_logged_in
    redirect_to posts_path unless current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if session[:user_id]
      redirect_to users_path
    end
    @user = User.new
    @is_login = request.path == login_path
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:alert] = "User created successfully. Please Log In."
      redirect_to login_path
    else
      flash.now[:alert] = "#{@user.errors.full_messages}"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find_by(id: params[:id])

    if @user.nil?
      flash[:alert] = "User not found."
      redirect_to users_path
    end
  end

  def login
    @user = User.find_by(email: user_params[:email])

    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      session[:user_name] = @user.name
      redirect_to posts_path
    else
      flash[:alert] = "Wrong email or password."
      @user = User.new
      @is_login = true
      redirect_to login_path
    end
  end

  def logout
    session[:user_id] = nil
    session[:user_name] = nil
    reset_current_user
    redirect_back(fallback_location: posts_path)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header id="header">
  <div>
    <div class="header-info">
      <p class="header-welcome">
        Welcome, 
        <% if session[:user_id] %>
          <%= session[:user_name] %>
        <% else %>
          Guest
        <% end %>
      </p>
      <p class="header-messages">
        <%= flash[:notice] %>
      </p>
      <p class="header-messages">
        <%= flash[:alert] %>
      </p>
    </div>
  </div>
  <div class="header-buttons">
    <%= link_to "Posts", posts_path, class: "header-button"%>
    <% if !session[:user_id] %>
      <%= link_to "Log in", login_path, class: "header-button"%>
      <%= link_to "Sign Up", new_user_path, class: "header-button"%>
    <% else %>
    <%= link_to "My Posts", my_posts_path, class: "header-button"%>
    <%= link_to "New Post", new_post_path, class: "header-button"%>
      <%= link_to "Log out", logout_path, class: "header-button"%>
    <% end %>
  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "L2 Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>EDIT POST</h1>

<%= form_with model: @post, local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title, value: @post.title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body, value: @post.body %>
  </div>
  <%= form.submit "Edit Post" %>
<% end %>

app/views/posts/index.html.erb
<h1>ALL POSTS</h1>

<% @posts.each do |post| %>
  <p class="post-info">
    <%= link_to post.title, post_path(post[:id]), class: "post-title" %>
    <br>
    <%= post.user.name %> - <%= post.created_at.strftime("%B %d, %Y") %>  
  </p>
<% end %>

app/views/posts/new.html.erb
<h1>NEW POST</h1>

<%= form_with model: @post, url: posts_path do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <%= form.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<div class="post-info">
  <h1>
    <%= @post.title.capitalize %>
  </h1>
  <h4>
    Author:
    <%= @post.user.name %>
  </h4>
</div>

<div class="post-body">
  <p>
    <%= @post.body.capitalize %>
  </p>
</div>

app/views/posts/user_posts.html.erb
<h1>YOUR POSTS</h1>

<% @posts.each do |post| %>
  <div>
  <p class="post-info">
    <%= link_to post.title, post_path(post[:id]), class: "post-title" %>
    <br>
    <%= post.created_at.strftime("%B %d, %Y") %>  
  </p>
  <%= link_to "Edit", edit_post_path(post[:id]) %>
  <%= link_to "Delete", post_path(post[:id]), data: { "turbo-method": :delete, confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/users/login.html.erb
<%= form_with model: @user, url: login_path do |form| %>
  <% if !@is_login %>
  <div>
    <%= form.label :name%>
    <%= form.text_field :name%>
  </div>
  <% end %>
  <div>
    <%= form.label :email%>
    <%= form.email_field :email%>
  </div>
  <div>
    <%= form.label :password%>
    <%= form.password_field :password%>
  </div>
  <%= form.submit "Sign In" %>
<% end %>

app/views/users/new.html.erb
<h1>
  <%= @is_login ? "Sign In" : "Sign Up" %>
</h1>

<%= form_with model: @user, url: @is_login ? login_path : users_path do |form| %>
  <% if !@is_login %>
  <div>
    <%= form.label :name%>
    <%= form.text_field :name%>
  </div>
  <% end %>
  <div>
    <%= form.label :email%>
    <%= form.email_field :email%>
  </div>
  <div>
    <%= form.label :password%>
    <%= form.password_field :password%>
  </div>
  <%= form.submit @is_login ? "Sign In" : 'Sign Up' %>
<% end %>

app/views/users/show.html.erb
<h1>USER INFO</h1>

<div>
  <p>
    Name: <%= @user.name %>
    <br> 
    Id: <%= @user.id %> 
  </p> 
</div>